/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;


import java.util.logging.Level;
import java.util.logging.Logger;
import com.dao.DaoTipoMantenimiento;

import com.modelo.TipoMantenimiento;
import static java.awt.Frame.ICONIFIED;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luism
 */
public class frmTipoMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form frmTipoMantenimiento
     */
    public frmTipoMantenimiento() {
        initComponents();
        tablaTipoMantenimiento();
    }
    
    TipoMantenimiento tipoM=new TipoMantenimiento();
    DaoTipoMantenimiento daotM=new DaoTipoMantenimiento();
    
    public void tablaTipoMantenimiento()
    {
        String [] columnas = {"id","Tipo"};
        Object [] obj=new Object[2];
        DefaultTableModel tabla = new DefaultTableModel(null,columnas);
        List ls;
       try
        {
            ls = daotM.MostrarTipoMantenimiento();
            for (int i=0; i<ls.size(); i++)
            {
                tipoM=(TipoMantenimiento)ls.get(i);
                obj[0]=tipoM.getIdTipoMantenimiento();
                obj[1]=tipoM.getTipoManteniento();
                
                tabla.addRow(obj);
            }
            ls=daotM.MostrarTipoMantenimiento();
            this.JTbTipoMantenimiento.setModel(tabla);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }
    }
    
    public void insertarTipoMantenimiento ()throws Exception
    {
        tipoM.setIdTipoMantenimiento(Integer.parseInt(this.txtIdTipoMantenimiento.getText()));
        
        tipoM.setTipoManteniento(this.txtTipoMantenimiento.getText());
        daotM.insertarTipoMantenimiento(tipoM);
        JOptionPane.showMessageDialog(null, "Datos insertados con exito");
        limpiar();
   }
    
    
     public void limpiar()
     {
        this.txtIdTipoMantenimiento.setText("");
        this.txtTipoMantenimiento.setText("");
     }
     
    public void llenarTabla()
    {
        int fila = this.JTbTipoMantenimiento.getSelectedRow();
        this.txtIdTipoMantenimiento.setText(String.valueOf(this.JTbTipoMantenimiento.getValueAt(fila,0)));
        this.txtTipoMantenimiento.setText(String.valueOf(this.JTbTipoMantenimiento.getValueAt(fila,1)));
    }
     
     public void modificar ()
     {
         try 
         {
            tipoM.setIdTipoMantenimiento(Integer.parseInt(this.txtIdTipoMantenimiento.getText()));
            tipoM.setTipoManteniento(this.txtTipoMantenimiento.getText());
            int SiONo=JOptionPane.showConfirmDialog(this, "Desea modificar el Tipo de Mantenimiento","Modificar Tipo de Mantenimiento",JOptionPane.YES_NO_OPTION);
            
             if (SiONo==0)
            {
                daotM.modificarTipoMantenimiento(tipoM);
                JOptionPane.showMessageDialog(rootPane, "Tipo de Mantenimiento modificado con exito","Confirmacion",JOptionPane.INFORMATION_MESSAGE);
                tablaTipoMantenimiento();
                limpiar();
            }
             
             else
             {
                 limpiar();
             }
         } 
        
         catch (Exception ex) 
         {
           ex.printStackTrace();
         }
     
     }
     
     public void eliminar()
     {
          try 
         {
            tipoM.setIdTipoMantenimiento(Integer.parseInt(this.txtIdTipoMantenimiento.getText()));
            int SiONo=JOptionPane.showConfirmDialog(this, "Desea eliminar el Tipo Persona?","Eliminar Tipo Persona",JOptionPane.YES_NO_OPTION);
            
             if (SiONo==0)
            {
                daotM.eliminarTipoMantenimiento(tipoM);
                JOptionPane.showMessageDialog(rootPane, "Tipo Mantenimiento eliminado con exito","Confirmacion",JOptionPane.INFORMATION_MESSAGE);
                tablaTipoMantenimiento();
                limpiar();
            }
             
             else
             {
                 limpiar();
             }
         } 
        
         
         catch (Exception ex) 
         {
           JOptionPane.showMessageDialog(rootPane, ex.toString(),"Error",JOptionPane.ERROR_MESSAGE);
                   
         }
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTipoMantenimiento = new javax.swing.JTextField();
        txtIdTipoMantenimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTbTipoMantenimiento = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("TIPO DE MANTENIMIENTO");

        jLabel4.setText("Código :");

        jLabel5.setText("Descripcion :");

        txtTipoMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoMantenimientoActionPerformed(evt);
            }
        });

        txtIdTipoMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTipoMantenimientoActionPerformed(evt);
            }
        });

        JTbTipoMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "TIPO MANTENIMIENTO"
            }
        ));
        JTbTipoMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTbTipoMantenimientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTbTipoMantenimiento);

        btnCrear.setText("Crear");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCrear)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdTipoMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTipoMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTipoMantenimientoActionPerformed

    private void txtTipoMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoMantenimientoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        try{
           insertarTipoMantenimiento();
        }
        catch (Exception e){
            Logger.getLogger(frmTipoMantenimiento.class.getName()).log(Level.SEVERE, null, e);
        }
        tablaTipoMantenimiento();
        
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
            modificar();     
                 
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
         eliminar(); 
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void JTbTipoMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTbTipoMantenimientoMouseClicked
         llenarTabla();
    }//GEN-LAST:event_JTbTipoMantenimientoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTbTipoMantenimiento;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdTipoMantenimiento;
    private javax.swing.JTextField txtTipoMantenimiento;
    // End of variables declaration//GEN-END:variables
}
